# Generated by Django 3.2.16 on 2023-01-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20230114_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
